### ISSUE TITLE
Better support for running from the repo

### ISSUE THREAD

**Issue by mtfurlan** [ominitay/shellsaber#14]
### Is your feature request related to a problem? Please describe.
I don't care to install shaber to outside of the repo, because this way I can see and fetch any changes easier, and running shaber is only a thing I want to do in very specific contexts so I don't see any benefit to having it on my path.

I just spent far too long debugging mods not working, and the problem turned out to be I had the correct version in `$repo/config`, but not `$HOME/.config/shaber/config`

### Describe the solution you'd like
Rename config to config.example, add config to gitignore, and put the first shaber config search path as `$(dirname "$0")/config`

### Additional context
If you're good with this I can do a PR.

**Comment by ominitay** [comment]
I've made a PR for my implementation of this at #15. Please tell me there if you are happy with the changes :)
