### ISSUE TITLE
Unable to download certain mods

### ISSUE THREAD

**Issue by CCF100** [Ominitay/ShellSaber#8]
### Describe the bug
Whenever I try to download BeatSaverDownloader, Ini Parser, or BS Utils, ShellSaber says that it's downloading the mod, then it just stops....
### Steps to reproduce the behavior:
Run `shaber m e BeatSaverDownloader -V`
Watcn it fail
### Expected behavior:
The download to work correctly
### Logs:
![image](https://user-images.githubusercontent.com/29297989/130335612-485ca9a2-e5fe-4d1a-9b69-65c3bcc1335a.png)

### System info:
Distro: Arch Linux
Beat Saber version: 1.16.4

**Comment by Ominitay** [comment]
Figured that out. Using `curl` to download URLs with spaces in them results in that error code 3. Using `wget` works. Will switch things over in the morning. Sorry I didn't notice that.

**Comment by Ominitay** [comment]
Should be fixed now.
